name: Update Dashboard Data

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas google-api-python-client google-auth-httplib2 google-auth-oauthlib
        
    - name: Set up Google credentials
      run: |
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
        echo "${{ secrets.GOOGLE_TOKEN }}" > token.json
        
    - name: Run data collection script
      run: python scripts/collect_data.py
        
    - name: Run magazine fetch script
      run: python scripts/fetch_magazines.py
        
    - name: Clean up credentials
      run: |
        # Remove sensitive files before committing
        rm -f credentials.json token.json
          
    - name: Commit and push if changed
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add data/
        git commit -m "Update dashboard data" || exit 0
        git push